---

- name: Debug msg
  debug:
    msg: 'Kibana version to install: {{ kibana_package_name }}{% if kibana_version is defined and kibana_version != ""  %}-{{ kibana_version }}{% endif %}'

- name: Ensure default Kibana is absent
  when: uninstall_default_kibana
  file:
    path: /etc/yum.repos.d/kibana.repo
    state: absent


- name: Ensure default Kibana repo is absent
  when: uninstall_default_kibana
  package:
    name: kibana
    state: absent

- name: add kibana repo
  template:
    src: kibana.repo
    dest: /etc/yum.repos.d/kibana-{{ kibana_repo_name }}.repo

- name: Install Kibana
  yum:
    name: '{{ kibana_package_name }}{% if kibana_version is defined and kibana_version != ""  %}-{{ kibana_version }}{% endif %}'
    state: present
    update_cache: yes
    allow_downgrade: true

- name: Ensure Kibana permissions
  file:
    path: /usr/share/kibana
    owner: kibana
    group: kibana
    recurse: true

- name: Copy the Configuration file
  template:
    src: kibana.yml
    dest: /etc/kibana/kibana.yml
    mode: 0644
  notify: restart kibana

- name: Make sure kibana is started
  systemd:
    name: kibana
    state: started
    enabled: yes

